# SPDX-License-Identifier: GPL-2.0-or-later

obj-y += __udivmodti4.o
obj-y += __udivdi3.o

obj-y += ctype.o
obj-y += string.o
obj-y += strtox.o

obj-y += io_buffer/io_buffer.o
obj-y += io_buffer/strtox.o
#obj-y += io_buffer/vsscanf.o
#obj-y += io_buffer/vsnprintf.o

include $(srctree)/scripts/makefile.build
