# SPDX-License-Identifier: GPL-2.0-or-later

obj-y += uart_core.o
obj-y += console.o
obj-y += acpi/

# Platform specific driver objects.

obj-y += uart/8250.o

include $(srctree)/scripts/makefile.build
